FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt install -y tzdata ca-certificates && rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common

# 将流水线上一步构建出的二进制文件直接 Copy 进镜像中
COPY ascend-device-plugin /usr/local/bin/ascend-device-plugin
RUN chmod +x /usr/local/bin/ascend-device-plugin

# 将 beagle-smi-npu 二进制打进镜像，供 initContainer 预置到宿主机
COPY beagle-smi-npu /usr/local/bin/beagle-smi-npu
RUN chmod +x /usr/local/bin/beagle-smi-npu

ENTRYPOINT ["ascend-device-plugin"]
